title: Application Updated
description: User updates the app Collected automatically!
collection: Segment Mobile Spec
properties:
  previous_version:
    type: string
    description: Previously recorded version
  previous_build:
    type: number
    description: Previously recorded build
  version:
    type: string
    description: Version installed
  build:
    type: number
    description: Build number of the installed app
