title: Application Installed
description: User first opens your mobile app. Collected automatically!
collection: Segment Mobile Spec
properties:
  version:
    type: string
    description: Version installed
  build:
    type: number
    description: Build number of the installed app
