title: Product Removed from Wishlist
description: User removed a product from the wish list
collection: Segment eCommerce Spec
properties:
  - name: brand
    type: string
    description: Brand of the product
  - name: category
    type: string
    description: Product category being viewed
  - name: coupon
    type: string
    description: Coupon code associated with the product
  - name: image_url
    type: string
    description: Image url of the product
  - name: name
    type: string
    description: Name of the product
  - name: position
    type: integer
    description: Position of product in the list
  - name: price
    type: number
    description: Price of the product
  - name: product_id
    type: string
    description: Database ID of the product
  - name: quantity
    type: integer
    description: Quantity of the product
  - name: sku
    type: string
    description: Sku of the product
  - name: url
    type: string
    description: URL of the product page for product
  - name: variant
    type: string
    description: Variant of the product
  - name: wishlist_id
    type: string
    description: Wishlist ID to which the product was added
  - name: wishlist_name
    type: string
    description: Wishlist name to which the product was added
