title: Product List Filtered
description: User filtered a product list or category
collection: Segment eCommerce Spec
properties:
  - name: category
    type: string
    description: Product category being viewed
  - name: filters
    type: array
    description: Product filters that the customer is using
    items:
      type: object
      properties:
        type:
          name: type
          type: string
          description: ID of the filter type being used
        value:
          name: value
          type: string
          description: ID of the selection chosen
  - name: list_id
    type: string
    description: Product list being viewed
  - name: products
    type: array
    description: Products displayed in the product list
    items:
      type: object
      properties:
        product_id:
          name: product_id
          type: string
          description: Product ID displayed in the list
        sku:
          name: sku
          type: string
          description: Product SKU displayed in the list
        category:
          name: category
          type: string
          description: Product Category displayed in the list
        name:
          name: name
          type: string
          description: Product Name displayed in the list
        brand:
          name: brand
          type: string
          description: Product Brand displayed in the list
        variant:
          name: variant
          type: string
          description: Product Variant displayed in the list
        price:
          name: price
          type: number
          description: Product Price displayed in the list
        quantity:
          name: quantity
          type: integer
          description: Product quantity displayed in the list
        coupon:
          name: coupon
          type: string
          description: Coupon code associated with the product
        position:
          name: position
          type: number
          description: Position of product in the list
        url:
          name: url
          type: string
          description: URL of the product page for product in the list
        image_url:
          name: image_url
          type: string
          description: Image url of the product in the list
  - name: sorts
    type: array
    description: Product sorting the customer is using
    items:
      type: object
      properties:
        type:
          name: type
          type: string
          description: ID of the sort type being used
        value:
          name: value
          type: string
          description: ID of the selection type being used
