name: build-docs

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

  workflow_dispatch:

jobs:
  build-docs-site:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/${{github.repository_owner}}/schema-tools:latest
      credentials:
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}
      env:
        DEPLOY_GITHUB_URL: ${{github.repositoryUrl}}
        DEPLOY_GITHUB_TOKEN: ${{secrets.DEPLOY_GITHUB_TOKEN}}
        DEPLOY_GITHUB_USER: ${{secrets.DEPLOY_GITHUB_USER}}
        DEPLOY_GITHUB_USER_NAME: ${{secrets.DEPLOY_GITHUB_USER_NAME}}
        DEPLOY_GITHUB_USER_EMAIL: ${{secrets.DEPLOY_GITHUB_USER_EMAIL}}
    steps:
      - name: Build static docs site and deploy to GH Pages
        run: |
          cd /usr/app
          ./build-and-publish-docs.sh

  build-tracking-plans:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/${{github.repository_owner}}/schema-tools:latest
      credentials:
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}
      env:
        DEPLOY_GITHUB_URL: ${{github.repositoryUrl}}
        DEPLOY_GITHUB_TOKEN: ${{secrets.DEPLOY_GITHUB_TOKEN}}
        DEPLOY_GITHUB_USER: ${{secrets.DEPLOY_GITHUB_USER}}
        DEPLOY_GITHUB_USER_NAME: ${{secrets.DEPLOY_GITHUB_USER_NAME}}
        DEPLOY_GITHUB_USER_EMAIL: ${{secrets.DEPLOY_GITHUB_USER_EMAIL}}
        SEGMENT_WORKSPACE: ${{secrets.SEGMENT_WORKSPACE}}
        SEGMENT_CONFIG_API_TOKEN: ${{secrets.SEGMENT_CONFIG_API_TOKEN}}
    steps:
      - name: Build tracking plans and deploy to Segment
        run: |
          cd /usr/app
          ./build-and-deploy-tracking-plans.sh
