name: build-docs

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/${{github.repository_owner}}/schema-tools:latest
      credentials:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      env:
        DEPLOY_GITHUB_USER: ${{secrets.DEPLOY_GITHUB_USER}}
        DEPLOY_GITHUB_TOKEN: ${{secrets.DEPLOY_GITHUB_TOKEN}}
        DEPLOY_GITHUB_URL: ${{github.repositoryUrl}}
    steps:
      - name: Build and deploy
        run: |
          cd /usr/app
          ./build-and-publish-docs.sh
