name: Process Schema Pull Request
on:
  pull_request:
    branches: ['main']

jobs:
  add-triage-labels:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
    - uses: actions/labeler@v4
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"

  print-env-variabes:
    name: Print Github Variables
    runs-on: ubuntu-latest
    steps:
      - name: Print Github Variables
        run: |
          echo "GITHUB_WORKFLOW:$GITHUB_WORKFLOW"
          echo "GITHUB_EVENT_NAME:$GITHUB_EVENT_NAME"
          echo "GITHUB_EVENT_PATH:$GITHUB_EVENT_PATH"
          echo "GITHUB_WORKSPACE:$GITHUB_WORKSPACE"
          echo "GITHUB_SHA:$GITHUB_SHA"
          echo "GITHUB_REF:$GITHUB_REF"
          echo "GITHUB_HEAD_REF:$GITHUB_HEAD_REF"
          echo "Default branch: ${{github.event.repository.default_branch}}"
      - name: Print complete webhook event payload
        run: cat $GITHUB_EVENT_PATH
        
  create-impact-report:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/${{github.repository_owner}}/schema-tools:latest
      credentials:
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}
      env:
        DEPLOY_GITHUB_URL: ${{github.repositoryUrl}}
        DEPLOY_GITHUB_TOKEN: ${{secrets.DEPLOY_GITHUB_TOKEN}}
        DEPLOY_GITHUB_USER: ${{secrets.DEPLOY_GITHUB_USER}}
        DEPLOY_GITHUB_USER_NAME: ${{secrets.DEPLOY_GITHUB_USER_NAME}}
        DEPLOY_GITHUB_USER_EMAIL: ${{secrets.DEPLOY_GITHUB_USER_EMAIL}}
        GITHUB_PR_FROM_REF: ${{github.head_ref}}
        GITHUB_PR_TO_REF: ${{github.event.repository.default_branch}}
    steps:
      - name: Generate impact report and output to job summary
        run: |
          IMPACT_REPORT=`/usr/app/scripts/create-impact-report.sh`
          echo "\`\`\`json" >> $GITHUB_STEP_SUMMARY
          echo $IMPACT_REPORT >> $GITHUB_STEP_SUMMARY
          echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
