name: Process Schema Pull Request
on:
  pull_request:
    branches: ['main']

jobs:
  add-triage-labels:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
    - uses: actions/labeler@v4
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"

  create-impact-report:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/${{github.repository_owner}}/schema-tools:latest
      credentials:
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}
      env:
        DEPLOY_GITHUB_URL: ${{github.repositoryUrl}}
        DEPLOY_GITHUB_TOKEN: ${{secrets.DEPLOY_GITHUB_TOKEN}}
        DEPLOY_GITHUB_USER: ${{secrets.DEPLOY_GITHUB_USER}}
        DEPLOY_GITHUB_USER_NAME: ${{secrets.DEPLOY_GITHUB_USER_NAME}}
        DEPLOY_GITHUB_USER_EMAIL: ${{secrets.DEPLOY_GITHUB_USER_EMAIL}}
        GITHUB_PR_FROM_REF: ${{github.head_ref}}
        GITHUB_PR_TO_REF: ${{github.ref}}
    steps:
      - name: Generate impact report and output to job summary
        run: |
          IMPACT_REPORT=`/usr/app/scripts/create-impact-report.sh`
          echo "\`\`\`json" >> $GITHUB_STEP_SUMMARY
          echo $IMPACT_REPORT >> $GITHUB_STEP_SUMMARY
          echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
